### ISSUE TITLE
Investigate if `return_types` is needed in `TimeEdit.find_reservations_all`

### ISSUE THREAD

**Issue by ernstwi** [SUNET/te-canvas#11]
The function find_reservations_all uses the api endpoint findReservations, which takes an argument return_types. This specifies what types of objects (attached to each reservation) we want to get.

This is the cause of a lot of code surrounding event template strings. So it would be a big opportunity for simplification if there was a way to simply get *all* objects. I am pretty sure I looked into this and found that there was not, but we should double check this.

**Comment by pnts-se** [comment]
A lot of the code surrounding template strings is removed since the users choose fields via interactive ui.
return_types is also a good thing since it avoids over-fetching.
