### ISSUE TITLE
Add warning text that event template is a global setting

### ISSUE THREAD

**Issue by ernstwi** [SUNET/te-canvas#15]
Right now event template settings (title, location, description) apply to the entire Canvas instance.

But they are configured in the same UI as course-specific settings (but in a different tab).

This might be confusing to users. Ideally we could create a separate LTI app just to manage the template settings, and only give access to this to Canvas admins, so that teachers do not touch them. Or perhaps we could limit permissions based on LTI "roles" so that only admins have access to this part of the existing app?

Short of this we should at least add a big warning.

**Comment by pnts-se** [comment]
#24 split template config in group and default, but we still do not prevent changing default config based on LTI role.
