### ISSUE TITLE
Add a list of available object types and fields to UI

### ISSUE THREAD

**Issue by ernstwi** [SUNET/te-canvas#7]
When creating an event template you need to know which object are available and what fields they have. This info is available on TimeEdit but it would be good if we can present it to the users directly.

I just did this manually for one client, with the following TimeEdit API calls:

```python
types=client.service.findTypes(login=login,ignorealias=True)
res=[{'name': x['name'], 'extid': x['extid'], 'fields': sorted(client.service.getAllFields(login=login,type=x['extid']))} for x in types]
pprint.pp(res, sort_dicts=False)
```

So adding an API endpoint that does this and presenting it in the UI would be good.

**Comment by pnts-se** [comment]
We now use interactive ui for choosing fields.
This issue is solved by #21
